# Galapix - an image viewer for large image collections
# Copyright (C) 2018 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: ubuntu:focal

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -qq update
  - apt-get -qq -y install lsb-release
  - lsb_release -a
  - apt-get -qq -y install
    build-essential
    cmake
    g++-10
    clang-10
    clang-tidy-10

.build_argparser_template: &build_argparser
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DBUILD_TESTS=ON
    - make VERBOSE=1
    - make test VERBOSE=1 ARGS="-V"

build:gcc:release:
  <<: *build_argparser
  variables:
    CXX: "g++-10"
    BUILD_TYPE: "Release"

build:clang:release:
  <<: *build_argparser
  variables:
    CXX: "clang++-10"
    BUILD_TYPE: "Release"

build:gcc:debug:
  <<: *build_argparser
  variables:
    CXX: "g++-10"
    BUILD_TYPE: "Debug"

build:clang:debug:
  <<: *build_argparser
  variables:
    CXX: "clang++-10"
    BUILD_TYPE: "Debug"

build:clang-tidy:
  <<: *build_argparser
  variables:
    CXX: "clang++-10"
    BUILD_TYPE: "Debug"
    CLANG_TIDY: "ON"
    CLANG_TIDY_FIX: "OFF"

# EOF #
